# Naive_Bayes

## import dataset

In [3]:
import pandas as pd
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [5]:
dataset['Purchased'].unique()

array([0, 1], dtype=int64)

In [6]:
# ax = dataset[dataset['Purchased'] == 0].plot(kind='scatter', x='Age', y='EstimatedSalary', color='red', s=10);
# dataset[dataset['Purchased'] == 1].plot(kind='scatter', x='Age', y='EstimatedSalary', color='blue', s=10, ax=ax)

## clreaning

In [45]:
# clean the data

## encoding

In [48]:
# encode the data

## define x , y

In [8]:
import numpy as np
X = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

## spliting

In [10]:
### finding best random state 

# from sklearn.model_selection import train_test_split
# from sklearn.naive_bayes import GaussianNB
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import accuracy_score

# import time
# t1 = time.time()
# lst = []
# for i in range(1,100):
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=i) 
#     sc = StandardScaler().fit(X_train)
#     X_train = sc.transform(X_train)
#     X_test = sc.transform(X_test)
#     nb = GaussianNB()
#     nb.fit(X_train, y_train)
#     yhat_test = nb.predict(X_test)
#     acc = accuracy_score(y_test, yhat_test)
#     lst.append(acc)
# t2 = time.time()
# print(f"run time: {round((t2 - t1) / 60 , 0)} min")
# print(f"accuracy_score = {round(max(lst),2)}")
# print(f"random_state = {np.argmax(lst) + 1}")

run time: 0.0 min
accuracy_score = 0.95
random_state = 24


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

## scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## fit the model

In [15]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

## predict test data

In [17]:
yhat_test = nb.predict(X_test)

## evaluate the model

In [19]:
from sklearn.metrics import accuracy_score
print("Accuracy_score (train data): ", accuracy_score(y_train, nb.predict(X_train)))
print("Accuracy_score (test data): ", accuracy_score(y_test, yhat_test))

Accuracy_score (train data):  0.8633333333333333
Accuracy_score (test data):  0.93


In [20]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test, yhat_test)

array([[61,  2],
       [ 5, 32]], dtype=int64)

In [21]:
print(classification_report(y_test, yhat_test))

              precision    recall  f1-score   support

           0       0.92      0.97      0.95        63
           1       0.94      0.86      0.90        37

    accuracy                           0.93       100
   macro avg       0.93      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100



## predict new data

In [23]:
nb.predict(sc.transform([[35,70000]]))

array([0], dtype=int64)

## save the model

In [25]:
# import joblib
# joblib.dump(nb, 'nb_model.pkl')

## load the model

In [27]:
# import joblib
# nb = joblib.load('nb_model.pkl')