# Multiple Linear Regression

In [1]:
# from google.colab import files
# up = files.upload()

## import dataset

In [2]:
import pandas as pd
df = pd.read_csv('dataset.csv')
df = df[['A', 'B', 'C', 'T']]
df.head()

A  B     C    T
0  2.0  4   8.5  196
1  2.4  4   9.6  221
2  1.5  4   5.9  136
3  3.5  6  11.1  255
4  3.5  6  10.6  244

In [3]:
# df.info()

# cleaning

In [4]:
# clean the data

# encoding

In [5]:
# encode the data

# define x , y

In [6]:
import numpy as np
x = np.array(df[['A', 'B', 'C']])
y = np.array(df['T'])

# x = df[['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_COMB']].values
# y = df['CO2EMISSIONS'].values

In [7]:
y[:5]

array([196, 221, 136, 255, 244], dtype=int64)

## spliting

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

## scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(x_train)

In [10]:
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

## fit train data

In [11]:
# def param
# fit_intercept=True, copy_X=True, n_jobs=None, positive=False

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train, y_train)

In [14]:
print(mlr.intercept_)
print(mlr.coef_)

256.2187499999999
[16.20130859 12.55446815 33.38071933]


In [15]:
### K-fold cross validation

# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import GridSearchCV

# parameters = {
#     '': [],
#     '': []
# }

# lr = LinearRegression()
# gs = GridSearchCV(estimator=lr, param_grid=parameters, cv=5)

# gs.fit(x_train, y_train)

# best_params = gs.best_params_
# print(best_params)

## predict test data

In [16]:
yhat_test = mlr.predict(x_test)

## evaluate the model

In [17]:
from sklearn.metrics import r2_score
print("r2-score: %0.2f" % r2_score(y_test, yhat_test))

r2-score: 0.87


In [22]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(f"MSE: {mean_squared_error(y_test, yhat_test)}")
print(f"MAE: {mean_absolute_error(y_test, yhat_test)}")

MSE: 534.3107477423459
MAE: 16.910810786461692


## predict new data

In [19]:
mlr.predict(sc.transform([[2, 4, 8.5]]))

array([198.32166017])

## save the model

In [20]:
# import joblib
# joblib.dump(mlr, 'mlr_model.pkl')

## load the model

In [21]:
# import joblib
# mlr = joblib.load('mlr_model.pkl')